site_name: IRC Docs
site_url: https://ircdocs.hahota.net/
nav:
  - Home: index.md
  - Rules: rules.md
  - Commands: commands.md
  - Moderator Guide: moderatorguide.md
extra_css:
  - css/exter.css
theme: bootstrap386
